[parity]
chain = "/etc/parity/chain-config.json"
base_path = "/var/lib/parity"
[network]
port = 30300
[rpc]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8450